### ISSUE TITLE
Curious why xml2js takes 30ms to parse what takes xml2json 3ms

### ISSUE THREAD

**Issue by brandonros** [Leonidas-from-XIV/node-xml2js#220]
Are there some default options? It's any data I pass it.

**Comment by Leonidas-from-XIV** [comment]
Might be all kinds of reasons, I suppose one of the main reasons is that it uses expat, a parser written in C whereas xml2js uses sax-js, which is written purely in JavaScript.

Both approaches have their pros and cons.

**Comment by brandonros** [comment]
That's got to be what it was! I wasn't sure. Sorry for the issue!

**Comment by Leonidas-from-XIV** [comment]
I mean, it is possible that xml2js *could* be made faster - it is currently focusing more on a convenient way to be used and not so much on performance. I didn't use much benchmarking because usually it is "fast enough" and for cases where you have massive amounts of data, it might not be the best tool (but parsing a massive XML into a massive in-memory data structure is probably not the best way to go about it).

**Comment by brandonros** [comment]
I was doing a lot of work with e-commerce APIs that arrived over SOAP. It was locking up like crazy when it got to the ~100kb strings. I had to write my own SOAP wrapper just to drop the ‘soap’ package.

**Comment by Leonidas-from-XIV** [comment]
I heard some people had luck with giving more memory to their systems (there was an issue about that), as storing a big object tree is memory intensive. Seems to have solved their performance issues.

**Comment by brandonros** [comment]
My issue was entirely related to CPU usage and time taken to parse the XML.
