### ISSUE TITLE
Getting innermost value as a string

### ISSUE THREAD

**Issue by efkan** [Leonidas-from-XIV/node-xml2js#258]
**node-xml2js** is the most famous XML tool for Node.js and I'm using in my project. Thanks.
I was wondering why innermost value of the object in an array**?** There must be a reason; which I couldn't find.
Nevertheless I'm explaining. The below examples show us that we know where is innermost value at and it should be written as a String value like `["401"]` and `["Unauthorized"]`. So, why innermost values don't come as String like `"401"` and `"Unauthorized"`**?**

An XML for example;

	<Response>
		<Error>
			<Code>401</Code>
			<Message>Unauthorized</Message>
		</Error>
		<Result></Result>
	</Response>
 

Transformed JS object ;

	{
		Response: [
			{ 
				Error: [
					Code: ["401"],
					Message: ["Unauthorized"]
				],
				Result: [ "" ]
			}
		]
	}

**Comment by rok-star** [comment]
It's the way how parser works for every xml node. Node body is always a children of it, represented as an array. Parser doesn't try to recognize the end of tree, it just works recursively.

**Comment by gerrard00** [comment]
If you don't want any arrays generated for single elements, you can set the option `explicitArray` to false. That generates:

```js
{
    Response: {
        Error: {
            Code: '401',
            Message: 'Unauthorized'
        },
        Result: ''
    }
}
```

If you only want to disable the generation of arrays for leaf nodes (that was my use case), you might be interested in my PR. It's linked above.

Using the option I added in my patch, you would get the following object from your sample xml:

```xml
{
    Response: {
        Error: [{
            Code: '401',
            Message: 'Unauthorized'
        }],
        Result: ''
    }
}
```

Note that `Error` is still an array in this case. I needed that functionality, which is why I wrote the patch.

**Comment by efkan** [comment]
Thank you @gerrard00 ,
I've already been using with `expilictArray` option. Just I thought, innermost value can be caught and xml2js may be arranged with this.
Best.

**Comment by gerrard00** [comment]
Check out my patch if you have a chance, that's pretty much what it does.
