### ISSUE TITLE
Only converts the first element

### ISSUE THREAD

**Issue by jreina** [Leonidas-from-XIV/node-xml2js#313]
I have files with multiple root elements that I would like to convert to a collection of JS objects. Currently when I pass in the entire text of the file, only the first element is converted.

Is this the expected behavior?

Are there any options, documented or otherwise, that I could pass in to change this behavior?

Regards,

**Comment by Leonidas-from-XIV** [comment]
The XML standard only allows one root element, that's why it only parses the first. This is expected behaviour (I am suprised how lenient it is, really, since I would've expected to reject the input as not being well-formed).

What you could do is to wrap your root elements in a new root element, which would satisfy the XML spec and the parser.

HTH!

**Comment by jreina** [comment]
Thanks for the quick response! I didn't realize the XML standard limited to a single root element, but thanks for the hint.

Thanks again for your help!

Regards,
