### ISSUE TITLE
Help with WIN 10 install

### ISSUE THREAD

**Issue by RonJTon** [Leonidas-from-XIV/node-xml2js#347]
I have nodejs installed and I want to run 'KiCad_BOM_Wizard-master' but it cannot find xml2js.  I have tried running 'npm install xml2js' but get errors.  I have included a ZIP of the log file.  

Thanks,
Ron
[npm-debug.zip](https://github.com/Leonidas-from-XIV/node-xml2js/files/625400/npm-debug.zip)

**Comment by graphnode** [comment]
A bit late but better than never:

You were running `npm install xml2js` in the xml2js source code directory.
Change into the correct directory ('KiCad_BOM_Wizard-master'?) and try again.

In this case, since the [package.json of KiCad_BOM_Wizard](https://github.com/HashDefineElectronics/KiCad_BOM_Wizard/blob/master/package.json) seems to be correctly written with the proper dependencies, you just need to type `npm install` to make it work. All node.js projects work like this.
