### ISSUE TITLE
explicitArray=true (default) doesn't put child elements of root element into an array

### ISSUE THREAD

**Issue by coolheinze** [Leonidas-from-XIV/node-xml2js#376]
All elements are put nicely into arrays - except for the children of the root element.

**Comment by coolheinze** [comment]
These files demonstrate the problem.

[examples.zip](https://github.com/Leonidas-from-XIV/node-xml2js/files/928153/examples.zip)

**Comment by jcsahnwaldt** [comment]
The deeper issue here is that the structure of JS objects and XML documents don't quite match. Differences relevant to this issue:

- An XML element can contain multiple elements with the same name. A JS object can contain at most one property with a certain name.
  - That's why xml2js usually creates JS properties whose values are arrays. (Unless `explicitArray` is false, but that's not the case here.)
  - For example, if an XML element contains six `Asset` elements, the corresponding JS object will have an `Asset` property whose value is an array with six elements.
- An XML document must have exactly one root element. JS in general does not distinguish between root objects and nested objects.
  - But xml2js does (a bit), because it has to work with XML.

Because every well-formed XML document must have exactly one root element, the root property of the JS object created by xml2js will always have exactly one value. Because it will always have exactly one value, there's no need to make it an array.

I unpacked your ZIP file and stripped everything but the root element and a few of its direct children:

---
`what-I-got.json`
```json
{
  "ADI": {
    "Metadata": [
      {
      }
    ],
    "Asset": [
      {
      },
      {
      }
    ]
  }
}
```

---
`what-I-expected.json`
```json
{
  "ADI": [
    {
      "Metadata": [
        {
        }
      ]
    },
    {
      "Asset": [
        {
        },
        {
        }
      ]
    }
  ]
}
```

---

These would correspond to XML with the following structure:

---
`what-I-got.xml`
```xml
<ADI>
  <Metadata/>
  <Asset/>
  <Asset/>
</ADI>
```

---
`what-I-expected.xml`
```xml
<ADI>
  <Metadata/>
</ADI>
<ADI>
  <Asset/>
  <Asset/>
</ADI>
```

This isn't a well-formed XML document because it has two root elements.

**Comment by jcsahnwaldt** [comment]
I unpacked your ZIP file and stripped everything but the root property and a few of its direct children.

---
`examples.zip`, file `what-I-got.json`
```json
{
  "ADI": {
    "Metadata": [
      {
      }
    ],
    "Asset": [
      {
      },
      {
      }
    ]
  }
}
```
This would correspond to XML with the following structure:
```xml
<ADI>
  <Metadata/>
  <Asset/>
  <Asset/>
</ADI>
```

---
`examples.zip`, file `what-I-expected.json`
```json
{
  "ADI": [
    {
      "Metadata": [
        {
        }
      ]
    },
    {
      "Asset": [
        {
        },
        {
        }
      ]
    }
  ]
}
```
This would correspond to XML with the following structure:
```xml
<ADI>
  <Metadata/>
</ADI>
<ADI>
  <Asset/>
  <Asset/>
</ADI>
```

This isn't a well-formed XML document because it has two root elements.

**Comment by jcsahnwaldt** [comment]
@coolheinze I hope this clears things up a bit. If you still have questions, let me know. Otherwise, please close the issue. Thanks!

**Comment by coolheinze** [comment]
@jcsahnwaldt Sure. TBH, I've been working on other projects for a year now, so forgive me, if I am a bit rusty. At any rate, there's no reason for me to keep the issue open, so I'll just close it. If something does come up again some day, I can always reopen.

Thanks for the thorough response!
