### ISSUE TITLE
Children are duplicated with certain options

### ISSUE THREAD

**Issue by Telokis** [Leonidas-from-XIV/node-xml2js#404]
Here is the input XML :

```xml
<model name="Hello">
    <position x="330" y="650" />
</model>
```

Here is the output :

```json
{
    "$": {
        "name": "Hello"
    },
    "#name": "model",
    "$$": [
        {
            "$": {
                "x": 330,
                "y": 650
            },
            "#name": "position"
        }
    ],
    "position": [
        {
            "$": {
                "x": 330,
                "y": 650
            }
        }
    ]
}
```

And, finally, here are the options I used :

```js
const parseNumbers = val => xml2js.processors.parseNumbers(val);
const removeCR = val => val.replace(/\r/g, "");
const parserOptions = {
  trim: true,
  explicitChildren: true,
  preserveChildrenOrder: true,
  attrValueProcessors: [removeCR, parseNumbers],
  valueProcessors: [removeCR, parseNumbers],
};
```

As you can see, the node "position" ends up to be both in the children and a direct property of the object.

**Comment by lensbart** [comment]
From the README: `preserveChildrenOrder` (default `false`): Modifies the behavior of `explicitChildren` so that the value of the "children" property becomes an ordered array. When this is `true`, every node will also get a `#name` field whose value will correspond to the XML `nodeName`, so that you may iterate the "children" array and still be able to determine node names. The named (and potentially unordered) properties are also retained in this configuration at the same level as the ordered "children" array. Added in 0.4.9.
