### ISSUE TITLE
Billion laughs attack

### ISSUE THREAD

**Issue by drac94** [Leonidas-from-XIV/node-xml2js#415]
Does this library take care of this kind of attack?

https://www.wikiwand.com/en/Billion_laughs_attack

I have tested it with the input below that I got form the wikipedia page

```
<?xml version="1.0"?>
<!DOCTYPE lolz [
 <!ENTITY lol "lol">
 <!ELEMENT lolz (#PCDATA)>
 <!ENTITY lol1 "&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;">
 <!ENTITY lol2 "&lol1;&lol1;&lol1;&lol1;&lol1;&lol1;&lol1;&lol1;&lol1;&lol1;">
 <!ENTITY lol3 "&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;">
 <!ENTITY lol4 "&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;">
 <!ENTITY lol5 "&lol4;&lol4;&lol4;&lol4;&lol4;&lol4;&lol4;&lol4;&lol4;&lol4;">
 <!ENTITY lol6 "&lol5;&lol5;&lol5;&lol5;&lol5;&lol5;&lol5;&lol5;&lol5;&lol5;">
 <!ENTITY lol7 "&lol6;&lol6;&lol6;&lol6;&lol6;&lol6;&lol6;&lol6;&lol6;&lol6;">
 <!ENTITY lol8 "&lol7;&lol7;&lol7;&lol7;&lol7;&lol7;&lol7;&lol7;&lol7;&lol7;">
 <!ENTITY lol9 "&lol8;&lol8;&lol8;&lol8;&lol8;&lol8;&lol8;&lol8;&lol8;&lol8;">
]>
<lolz>&lol9;</lolz>
```
And I get the following error:

`Error: Invalid character entity Line: 0 Column: 676 Char: ;`

**Comment by jcsahnwaldt** [comment]
xml2js is safe against this attack, because the underlying library sax-js simply ignores custom DTD `<!ENTITY ...>` definitions: "It's possible to define additional entities in XML by putting them in the DTD. This parser doesn't do anything with that." https://github.com/isaacs/sax-js#regarding-doctypes-and-entitys

The error occurs because sax-js doesn't recognize `&lol9;` as a valid entity.

**Comment by jcsahnwaldt** [comment]
I think the issue can be closed.
