### ISSUE TITLE
XML to JS - all values are in arrays

### ISSUE THREAD

**Issue by dainchatel** [Leonidas-from-XIV/node-xml2js#433]
I know you said to send an e-mail instead of opening an issue, but I could not find your e-mail address, so here I am. Thanks for a great and helpful library. 

I have read through the docs several times, and looked through the issues, and I'm not seeing anything about my problem. When I run some XML through the library, it brings back a deep object, but every single value is inside of an array, like so:

'a:FirstName': [ 'Dain' ],
'a:LastName': [ 'Chatel' ],
'a:Phone' : [  {
   primary: [ '123-456-7890']
}  ]

As you can imagine, this makes mapping a bit difficult. I have tried to add a function in valueProcessors that extracts the values from the arrays, but it doesn't seem to think there ARE any arrays, so I assume it's iterating over all the values inside them already. 

Hopefully someone spots my obvious mistake or misunderstanding of the library. Thanks!

**Comment by Leonidas-from-XIV** [comment]
I'd argue that this is the correct behaviour, since the parser does not know that there will never be a second element in `a:FirstName`, so it puts it in an array.

You can turn this off by setting `explicitArray` to `false` but I specifically recommend against it.

**Comment by dainchatel** [comment]
Thank you! That makes sense - I have some parent nodes coming back, so I do need their children in arrays.

**Comment by peternann** [comment]
@Leonidas-from-XIV - Can I suggest that the behaviour of 'every property is an array' gets mentioned VERY EARLY in the product documentation.

I get that this is probably the most RELIABLE behaviour, but it sure ain't the most EXPECTED behaviour.

Most first time users (like me...) will read the top half of the README, and think that xml2js is broken, because a TONNE of stuff that doesn't need to be in arrays, is in arrays. The javascript objects seem to simply not match the XML objects, because there are arrays everywhere.
So it would be really helpful to explain this behaviour (which changed at V0.2?) early on in doco.

**Comment by Leonidas-from-XIV** [comment]
@peternann I think such a documentation change is fair, would you submit a PR with your suggestion on a draft wording please?
