### ISSUE TITLE
Ignore invalid entity name

### ISSUE THREAD

**Issue by swwind** [Leonidas-from-XIV/node-xml2js#485]
I found it throw errors while parsing this invalid example:

```xml
<x>GL&HF</x>
```

```plain
Error: Invalid character in entity name
```

I know it's an invalid format, but in some time we should accept this mistake and parse it as blow:

```js
{ x: "GL&HF" }
```

Hope to enhance it.

**Comment by Leonidas-from-XIV** [comment]
I think it is a mistake to try to parse faulty XML because it adds all kinds of unspecified semantics to the parser, like what does it do when X is wrong, what when Y is wrong? What if changing the implementation changes these semantics.

I think if you want to parse these entities, you should clean up the data before, then you'll know what is going on exactly.
