### ISSUE TITLE
Allow to remove namespace prefixes from xml nodes

### ISSUE THREAD

**Issue by shadeglare** [Leonidas-from-XIV/node-xml2js#87]
Could you provide the ability to remove namespace prefixes from nodes.

For example:

Translate the xml below

``` xml
<f:table xmlns:f="http://www.w3schools.com/furniture"> 
  <f:name>African Coffee Table</f:name>                
  <f:width>80</f:width>                                
  <f:length>120</f:length>                             
</f:table>
```

to a json like:

``` json
{
  "table": {
    "$": {
      "xmlns:f": "http://www.w3schools.com/furniture"
    },
    "name": "African Coffee Table",
    "width": "80",
    "length": "120"
  }
}
```

Now it looks like:

``` json
{
  "f:table": {
    "$": {
      "xmlns:f": "http://www.w3schools.com/furniture"
    },
    "f:name": "African Coffee Table",
    "f:width": "80",
    "f:length": "120"
  }
}
```

**Comment by wisotzky** [comment]
I am just running into the same issue. Looks like a bug to me. You never know, what prefix place-holders are used in a XML document. So it might be "f:table" in one document and "xyz:table" in another or just "table" in the next. So this makes parsing the JSON output much to complex. The preferred method should be, to remove all xmlns prefixes - but to add the individual resolved xmlns to any individual element.

**Comment by mike-feldmeier** [comment]
I realize this is an old issue, but since it's open, there is a recent comment, and Google led me here, I'll add to the discussion.

If you're just looking to strip the namespace prefixes from the document, as is useful in cases where only a single namespace is being used, then that is already supported through the use of the **tagNameProcessors** option and the **stripPrefix** method included in the processors module:

    var parseString = require('xml2js').parseString;
    var stripPrefix = require('xml2js').processors.stripPrefix;
    
    parseString(xml, { tagNameProcessors: [ stripPrefix ] }, function(err, js) {
        if(err) throw err;
        console.dir(js, { depth: null });
    });

This doesn't support the above mentioned logging of namespaces, but that doesn't really appear to be useful anyway, since the entire request is about being able to process the tags without consideration for namespace, and knowing what namespaces were stripped isn't going to allow you to reconnect them.

Just my 2 cents anyway...

**Comment by jcsahnwaldt** [comment]
I guess this can be closed. `stripPrefix` is mentioned in a short sentence in [README.md](https://github.com/Leonidas-from-XIV/node-xml2js/blob/master/README.md#processing-attribute-tag-names-and-values), and while the last comment here by @mike-feldmeier is probably a great addition to that short sentence, the comment will probably still show up in Google results even when this issue is closed.

**Comment by munimanjunath** [comment]
When I defined the parser  as  var xml2jsParser = new xml2js.Parser({explicitArray : false});
above code is getting stuck

**Comment by myadzel** [comment]
You can pass params `tagNameProcessors` and `attrNameProcessors` for strip xmlns prefix from tags and attributes.

For example with function `stripPrefix`:

https://github.com/Leonidas-from-XIV/node-xml2js/blob/aefc64af9e9badbd0aade00814548f2ea33c9b4e/src/processors.coffee#L12

```js
const stripPrefix = xml2js.processors.stripPrefix;

const parser = new xml2js.Parser({
    tagNameProcessors: [ stripPrefix ],
    attrNameProcessors: [ stripPrefix ],
});
